### ISSUE TITLE
Remove dependency on Python 3.x

### ISSUE THREAD

**Issue by Doodlezoid** [Lord-Akkrand/Skyrim-NX-Toolkit#1]

**Comment by Lord-Akkrand** [comment]
It's gone.  If there are lingering trails, they can be caught and killed.
I can simply pack it all using PyInstaller and turn the whole toolkit into an exe with a single entry point.

**Comment by Lord-Akkrand** [comment]
It's gone. If there are lingering trails, they can be caught and killed.
I can simply pack it all using PyInstaller and turn the whole toolkit into an exe with a single entry point.
