### ISSUE TITLE
Remove requirement for Archive.exe

### ISSUE THREAD

**Issue by Doodlezoid** [Lord-Akkrand/Skyrim-NX-Toolkit#2]

**Comment by Lord-Akkrand** [comment]
Archive.exe is better than bsarch in that you list every file you want to add - it's necessary for the breaking up of large bsa files without a large amount of copying files around.

**Comment by Lord-Akkrand** [comment]
It no longer requires Archive.  If you have it, it will use it, but there's no specific advantage since we don't use compression.
