### ISSUE TITLE
Warning, cannot convert 0_master.hkx because <SSE hkx animation>

### ISSUE THREAD

**Issue by J7mbo** [Lord-Akkrand/Skyrim-NX-Toolkit#26]
I'm trying to convert USSEP. I'm following a [guide](https://gbatemp.net/threads/skyrim-mods-that-i-can-confirm-are-working.523839/page-5).

When it comes to using Skyrim-NX-toolkit, I have followed your instructions to place **HavokBehaviorPostProcess.exe** directly in the Utilities directory. However when running CONVERT_MOD, the error in the title is still shown. Screenshot:

![image](https://user-images.githubusercontent.com/2657310/55115077-e158c400-50e3-11e9-85e7-fdcd4c6e48ea.png)

Edit:

Looked through the code and found this: 

https://github.com/Lord-Akkrand/Skyrim-NX-Toolkit/blob/539599b4f21e5983229586874f1025056e0aafbd/Scripts/convert_hkx64.py#L11

... so I have literally no idea what "you can fish 32 bit equivalent" means, and where I would place these files etc.

**Comment by ThyWoof** [comment]
Please ensure you correctly followed the steps. Cannot reproduce:

1. Download USSEP;
2 Download USLEP and ensure you unarchive the BSA;
3 Run the Command;

Results using latest version:

D:\>\WORK\Skyrim-NX-Toolkit\CONVERT_MOD.BAT d:\USSEP d:\USLEP
Starting up...
toolkit.exe is set at "D:\WORK\Skyrim-NX-Toolkit\Scripts\dist\toolkit.exe"
texconv.exe exists in Utilites path
texdiag.exe exists in Utilites path
nvddsinfo.exe exists in Utilites path
Skyrim-NX-Toolkit v2.3.0, sys.argv <['D:\\WORK\\Skyrim-NX-Toolkit\\Scripts\\dist\\toolkit.exe', 'convert_mod', 'd:\\USSEP', 'd:\\USSEP_ConvertedAndPacked', 'd:\\USLEP']>
<d:\USSEP>
Logger Initialised d:\USSEP.log
Timer Started 2019-03-27 19:18:41
Skyrim-NX-Toolkit v2.3.0 - convert_mod
Convert Mod, ToolkitPath is D:\WORK\Skyrim-NX-Toolkit
Convert Mod, create empty folder at target
CreateTarget(d:\USSEP_ConvertedAndPacked)
Unpacking USSEP
Found 0 BSAs & 5838 loose files
Copied 5838/5838
Reconcile HKX
Matched 7/7 hkx files in the mod
Reconciled 7/7
Convert Path
Found 200 dds files to convert
Found 7 32-bit hkx files to convert
Found 0 64-bit hkx files to convert

**Comment by J7mbo** [comment]
@ThyWoof I followed your command, thanks for clearing this up, with both USSEP and then USLEP (dirs having been unpacked first with bsarch).

However, there's no ESP file generated. Looks like the error is:

> **There's a plugin-like path in your data, but no ESP matching it or listing it as a merge parent**

Note: I'm using the python version as exes wouldn't work (complaining about a missing python lib). Regardless, this shouldn't affect it. Here's the output:

> 
> C:\Users\James\Desktop\Skyrim-NX-Toolkit-master-NEWEST>PY_CONVERT_MOD.BAT C:\Users\James\Desktop\Skyrim-NX-Toolkit-master-NEWEST\USSEP_OLDRIM C:\Users\James\Desktop\Skyrim-NX-Toolkit-master-NEWEST\USLEEP_OLDRIM
> Starting up...
> toolkit.py is set at "C:\Users\James\Desktop\Skyrim-NX-Toolkit-master-NEWEST\Scripts\toolkit.py"
> Finding Python 3.x path
> Python 3.7.3
> Python is installed
> PYTHON3 is C:\Users\James\AppData\Local\Programs\Python\Python37-32\python.exe
> texconv.exe exists in Utilites path
> texdiag.exe exists in Utilites path
> nvddsinfo.exe exists in Utilites path
> Skyrim-NX-Toolkit v2.3.1, sys.argv <['C:\\Users\\James\\Desktop\\Skyrim-NX-Toolkit-master-NEWEST\\Scripts\\toolkit.py', 'convert_mod', 'C:\\Users\\James\\Desktop\\Skyrim-NX-Toolkit-master-NEWEST\\USSEP_OLDRIM', 'C:\\Users\\James\\Desktop\\Skyrim-NX-Toolkit-master-NEWEST\\USSEP_OLDRIM_ConvertedAndPacked', 'C:\\Users\\James\\Desktop\\Skyrim-NX-Toolkit-master-NEWEST\\USLEEP_OLDRIM']>
> <C:\Users\James\Desktop\Skyrim-NX-Toolkit-master-NEWEST\USSEP_OLDRIM>
> Logger Initialised C:\Users\James\Desktop\Skyrim-NX-Toolkit-master-NEWEST\USSEP_OLDRIM.log
> Timer Started 2019-03-28 20:04:51
> Skyrim-NX-Toolkit v2.3.1 - convert_mod
> Convert Mod, ToolkitPath is C:\Users\James\Desktop\Skyrim-NX-Toolkit-master-NEWEST
> Convert Mod, create empty folder at target
> CreateTarget(C:\Users\James\Desktop\Skyrim-NX-Toolkit-master-NEWEST\USSEP_OLDRIM_ConvertedAndPacked)
> Unpacking USSEP_OLDRIM
> Found 0 BSAs & 5635 loose files
> Copied 5635/5635
> Reconcile HKX
> Matched 7/7 hkx files in the mod
> Reconciled 7/7
> Convert Path
> Found 0 dds files to convert
> Found 7 32-bit hkx files to convert
> Found 0 64-bit hkx files to convert
> Found 0 txt files to convert
> Found 300 sound files to convert
> HKX 32-bit Processed 7/7 (7/0) success/failure.
> Sounds Processed 300/300 (300/0) success/failure.
> Pack Mod
> Files (2123) / Folders (4) to move
> Moved Files 2123/2123 Folders 4/4
> Cleanup old folders
> Build File List
> Prepared 2117/2117
> Run bsarch.exe
> Clean Up
> Build File List
> Prepared 7/7
> Run bsarch.exe
> Clean Up
> Build File List
> Prepared 3211/3211
> Run bsarch.exe
> Clean Up
> There's a plugin-like path <unofficial skyrim special edition patch.esp> in your data, but no ESP matching it or listing it as a merge parent
> Build File List
> Prepared 300/300
> Run bsarch.exe
> Clean Up
> Total Time Taken 0:02:50.256442

**Comment by J7mbo** [comment]
Okay, fixed.

For future readers, the exact problem that I was missing was:

You need to unpack the legendary edition bsas with bsarch unpack. You do NOT do this with the special edition.

Your command is then:

> CONVERT_MOD.bat <PATH_TO_ORIGINAL_SPECIAL_EDITION_DIR> <PATH_TO_UNPACKED_LWITH_BSARCH_EGENDARY_EDITION_DIR>

Bit of a weird one. Many thanks for helping me figure this out!
