### ISSUE TITLE
Unknown Audio Format on all .fuz files

### ISSUE THREAD

**Issue by Volkaru** [Lord-Akkrand/Skyrim-NX-Toolkit#41]
Every mod I try to convert with a .fuz file gives an error saying Unknown audio format.
Here is a screen shot of the conversion process skipping over all these files. This is a custom merged patch in the screen shot, but it gives the same error on any mod that has .fuz files. (Most custom voiced mods, followers, quests, etc.)
![Capture](https://user-images.githubusercontent.com/9113384/63950499-f3db7e80-ca30-11e9-839f-e4857c9b4a1f.PNG)

**Comment by ThyWoof** [comment]
Are you sure these FUZ files hasn’t already been converted? These signatures smell like NX ones, not PC.

Sound procedure is sound. Not a bug.

**Comment by Volkaru** [comment]
So it's just skipping them because they were already converted? Wasn't sure, thanks. I convert all my mods individually before making a merge patch. So that'd make sense.
