### ISSUE TITLE
"Could Not Apply Rule For 'filename'.psc"

### ISSUE THREAD

**Issue by Obsidianbone** [Lord-Akkrand/Skyrim-NX-Toolkit#46]
For some reason when trying to convert the "Race Compatibility Mod", i keep getting the same could not apply rule for mods in source\scripts\modname.psc no matter if i use he regular convert_mod or py_convert mod. Would anybody be able to shed some light on the issue?

**Comment by doodlum** [comment]
Ignore it. It's a source file which isn't used.
