### ISSUE TITLE
Voice Language Pack not working

### ISSUE THREAD

**Issue by Claudrk** [Lord-Akkrand/Skyrim-NX-Toolkit#8]
I install the Spanish Language Pack, but in-game voice still in english. The INI files generated by load_order.py by other languages (such as Skyrim_es.ini) not change sResourceArchiveList2 to "Skyrim - Voices_es0.bsa" but keep in "Skyrim - Voices_en0.bsa"

**Comment by Lord-Akkrand** [comment]
Apologies, that's an oversight on my part.  I'll look at fixing that up.

**Comment by Lord-Akkrand** [comment]
Fixed in v2.0.3

**Comment by Claudrk** [comment]
Thanks you, very much !
